apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-jz0a
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-jz0a
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-jz0a
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-jz0a
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-jz0a
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-raua-tenant/rhtap-demo-app/hacbs-test-project-jz0a@sha256:5c72a381de716f180c202d53509f6f919f8c730d7af79943c0a4150320c53d8e
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
